version: '3.1'

services:
  springboot:
    image: 966579203816.dkr.ecr.ap-south-1.amazonaws.com/springbootapp:VERSION
    environment:
      - AWS_ACCESS_KEY_ID=AKIA6CDE4F3UJMEIP4FO
      - AWS_SECRET_ACCESS_KEY=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
    
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=farhan
    - MONGO_DB_PASSWORD=far256164
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappbridge  
#     deploy:  # This will be considered only in docker swarm.
#       replicas: 2
#       update_config:
#         parallelism: 1
#         delay: 20s
#       restart_policy:
#         condition: on-failure
#         delay: 10s
#         max_attempts: 5

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=farhan
    - MONGO_INITDB_ROOT_PASSWORD=far256164
    volumes:
      - mongoebsvol:/data/db
    restart: always
    networks:
    - springappbridge
    
volumes:
  mongoebsvol:
    external: true
    
networks:
  springappbridge:
    external: true
