apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  namespace: dev-ns
  labels:
    app: springbootapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
        containers:
         - name: springbootcontainer
           image: farhanregistery/springbootapp:VERSION
           ports:
            - containerPort: 8080
           resources:
            requests:
              cpu: 0.25
              memory: 200Mi
            limits:
              cpu: 0.45
              memory: 300Mi
           env:
            - name: MONGO_DB_HOSTNAME
              value: mongoservice
            - name: MONGO_DB_USERNAME
              value: farhan
            - name: MONGO_DB_PASSWORD
              value: far256164
---
apiVersion: v1
kind: Service
metadata:
   name: springappservice
   namespace: dev-ns
spec:
  type: NodePort
  selector:
     app: springbootapp
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
       - name: mongocontainer
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: farhan
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: far256164
         volumeMounts:
           - mountPath: /data/db
             name: mongovol
      volumes:
        - name: mongovol
          nfs:
            server: 172.31.15.102
            path: /nfs_shares
---
apiVersion: v1
kind: Service
metadata:
   name: mongoservice
   namespace: dev-ns
spec:
  type: ClusterIP
  selector:
     app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
